// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trickler_API.Data;

#nullable disable

namespace Trickler_API.Migrations
{
    [DbContext(typeof(TricklerDbContext))]
    [Migration("20260205000000_AddAvailabilityTable")]
    partial class AddAvailabilityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trickler_API.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DaysOfWeekJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("days_of_week");

                    b.Property<string>("DatesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("dates");

                    b.Property<DateOnly?>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateOnly?>("Until")
                        .HasColumnType("date")
                        .HasColumnName("until_date");

                    b.HasKey("Id");

                    b.ToTable("availabilities");
                });

            modelBuilder.Entity("Trickler_API.Models.Trickle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("int")
                        .HasColumnName("availability_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.ToTable("trickles");
                });

            modelBuilder.Entity("Trickler_API.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TricklerId")
                        .HasColumnType("integer")
                        .HasColumnName("trickler_id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.HasKey("Id");

                    b.HasIndex("TricklerId");

                    b.ToTable("answers");
                });

            // relationships
            modelBuilder.Entity("Trickler_API.Models.Trickle", b =>
                {
                    b.HasOne("Trickler_API.Models.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Availability");
                });

            modelBuilder.Entity("Trickler_API.Models.Answer", b =>
                {
                    b.HasOne("Trickler_API.Models.Trickle", null)
                        .WithMany("Answers")
                        .HasForeignKey("TricklerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trickler_API.Models.Trickle", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
